// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPc6SIfMcgG3AigNStBzaHj5BmC95EXy4',
    appId: '1:505915912821:web:be2dbd10be0972666efe3c',
    messagingSenderId: '505915912821',
    projectId: 'smart-waste-d6fd8',
    authDomain: 'smart-waste-d6fd8.firebaseapp.com',
    storageBucket: 'smart-waste-d6fd8.firebasestorage.app',
    measurementId: 'G-TT9E9Y6XDT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgfoganiKz4g295kTMwmNMkFpuner9ohY',
    appId: '1:505915912821:ios:d8fe50ac7f46e79a6efe3c',
    messagingSenderId: '505915912821',
    projectId: 'smart-waste-d6fd8',
    storageBucket: 'smart-waste-d6fd8.firebasestorage.app',
    iosBundleId: 'com.alpha.alpha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgfoganiKz4g295kTMwmNMkFpuner9ohY',
    appId: '1:505915912821:ios:d8fe50ac7f46e79a6efe3c',
    messagingSenderId: '505915912821',
    projectId: 'smart-waste-d6fd8',
    storageBucket: 'smart-waste-d6fd8.firebasestorage.app',
    iosBundleId: 'com.alpha.alpha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPc6SIfMcgG3AigNStBzaHj5BmC95EXy4',
    appId: '1:505915912821:web:be347217bfdf8b586efe3c',
    messagingSenderId: '505915912821',
    projectId: 'smart-waste-d6fd8',
    authDomain: 'smart-waste-d6fd8.firebaseapp.com',
    storageBucket: 'smart-waste-d6fd8.firebasestorage.app',
    measurementId: 'G-RTX6RP6516',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKdhItgC22Q3pZDN8VPUSbECkxSMhQGWg',
    appId: '1:505915912821:android:0e6fac712312adec6efe3c',
    messagingSenderId: '505915912821',
    projectId: 'smart-waste-d6fd8',
    storageBucket: 'smart-waste-d6fd8.firebasestorage.app',
  );

}